In [1]:
!pip uninstall -y torchao
!pip install pandas numpy scikit-learn transformers bitsandbytes accelerate peft torch torchvision

Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Successfully uninstalled torchao-0.10.0
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.10.2)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.26.0+cu128)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.18.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch) (1.5.5)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 17.2 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.2

In [2]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils.class_weight import compute_class_weight

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.mps.is_available() else "cpu")

In [5]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/hate_train.csv")
df.head()

                                            sentence  label
0  Dla mnie faworytem do tytułu będzie Cracovia. ...      0
1  @anonymized_account @anonymized_account Brawo ...      0
2  @anonymized_account @anonymized_account Super,...      0
3  @anonymized_account @anonymized_account Musi. ...      0
4    Odrzut natychmiastowy, kwaśna mina, mam problem      0

In [6]:
print(df["label"].value_counts())

label
0    9190
1     851
Name: count, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df["sentence"].to_list(), df["label"].to_list(), test_size=0.10, random_state=42, stratify=df["label"])
X_train, X_eval, y_train, y_eval = train_test_split(X_train, y_train, test_size=1/9, random_state=42, stratify=y_train)
X_train, y_train

(['@anonymized_account @anonymized_account Wspaniały. Ale takiego Więckiewicza się można było spodziewać. Takiego Frycza - bynajmniej! Tu leży jego przewaga.',
  '@anonymized_account Tylko czemu link do tekstu z lutego? :P',
  '@anonymized_account @anonymized_account @anonymized_account Np to że Misiek i Zielak zainwestowali miliony w klub 😂',
  '@anonymized_account zjeby mówią że nie chodziło fizycznie o gotówkę, kurwa zero godności',
  '@anonymized_account A nastepni będą tacy jak Terlikowski spędzający czas w kolejce do psychiatry.',
  '@anonymized_account @anonymized_account @anonymized_account @anonymized_account @anonymized_account Po cholerę ci pytania? Przecież dostaniesz z PiSu na kartce.',
  'RT @anonymized_account wyniki sondy były do przewidzenia Polacy chcieli i chcą nadal reform sądów ! #bezretuszu',
  '@anonymized_account @anonymized_account Euro 2016 pokazało trochę co innego.',
  '@anonymized_account Ale skoro lubi śpiewać w samochodzie, więc zaśpiewa, to dlaczego z niego wyszedł? 🤔\\nI dlaczego ja to obejrzałam 😒',
  '@anonymized_account To czemu jej nie ogrzałeś ? :D',
  '@anonymized_account @anonymized_account I nie wpierdalacie się w paradę a będzie tylko lepiej.',
  '@anonymized_account A który zajmuje się kroczem?',
  '@anonymized_account Przełącz szybko, tam tylko dekadencja i hedonizm, zepsucie, gender',
  '@anonymized_account @anonymized_account To jest to coś przykryte torbą z IKEI?',
  '@anonymized_account jeden ale za to jaki :)',
  '@anonymized_account @anonymized_account usiedli od małego do dużego, wszystko jest przemyślane',
  '@anonymized_account Znajomy mówi, że jest mężem babci. Choć są rówieśnikami.',
  '@anonymized_account Ja mam protezę biodra i bajpasy, ale tolerancję na antybiotyk',
  '@anonymized_account Zawsze ta łyżka dziegciu co panie @anonymized_account 😁',
  'RT @anonymized_account Wszyscy sędziowie SN powinny pozwać do sądu Stanisława Piotrowicza. Skoro nazwał ich złodziejami, niech to przed sądem u…',
  '@anonymized_account Ale podszedł do Carrillo i widział to że mu chce ręke podać czy sobie to uroiłeś ?',
  'Uwaga❗️❗️❗️\\nW Nowym Sączu żałoba. Przegrał znicz, tj. PIS 😀😀😀',
  '@anonymized_account @anonymized_account tak na pewno mu już składali propozycje mimo że ma ważny kontrakt...',
  '@anonymized_account Ten caly śmietnik i tak ma nniejszą sprzedaż niż GW, gęgęgę zły tvn, i kwakwa kwa gazeta zła',
  '@anonymized_account To już ich nie dobijaj :P',
  '@anonymized_account @anonymized_account @anonymized_account Gołąb z wyborczej ? Czyli nie będziemy mogli słuchać 90% audycji, bo wyczerpaliśmy limit ?',
  '@anonymized_account @anonymized_account O! Paweł na TT, dzień dobry ;-)',
  '@anonymized_account Przykładnie ukarać i obciążyć kosztami odnowy elewacji..',
  '@anonymized_account tylko raz wymiekla i caly dzień internety, a tak wszędzie z nami, w  domu caly czas w swoim  pokoju albo z chlopakiem 13 lvl',
  '@anonymized_account A wlicza się tu też sezon mistrzowski Lecha...',
  '@anonymized_account ciągle tylko Kałużny i Kałużny',
  '@anonymized_account @anonymized_account @anonymized_account Za bardzo słupki spadły i Prezes was zjebał?',
  '@anonymized_account @anonymized_account Nie strasz, nie strasz.... Zajmij się kolegami pedofilami i kolegą Paetzem.',
  'RT @anonymized_account Wstyd mi za to co ja odpierdalałam w wieku 11 lat, pojebana jakaś byłam, chce te czasy wymazać ze swojej pamięci.',
  '@anonymized_account @anonymized_account To po co chodzi w lato w szaliku skoro go mecze legii nieintersesuja?',
  '@anonymized_account Też tylko raz byłeś w burdelu?',
  '- Na obiad zjem pączki.\\n- A faworki?\\n- Na deser 😎',
  '@anonymized_account @anonymized_account @anonymized_account Żeby zagłuszyć sumienie najpierw trzeba je mieć.',
  '@anonymized_account Wasz nowy nabytek ? :)',
  '@anonymized_account Skoro wymazal z pamięci to po co o tym gada??',
  '@anonymized_account @anonymized_account @anonymized_account Twój kolega już budował lotnisko w Radomiu. Twoje będzie takie samo.',
  '@anonymized_account wiem, domyśliłem się :) ale Marcyś na serio myśli że kiedyś będzie trenerem Wisły...',
  '@anonymized_account To jest bałwochwalstwo. Kupa betonu albo metalu sprofanowana..... To jest chore.',
  '@anonymized_account Tez jestem z września!!! Ja 20 😂',
  '@anonymized_account @anonymized_account Duda z Morawieckim już to za was zrobili. 😂😂😂😂😂😂',
  '@anonymized_account Kończyłeś już kilka razy 😂',
  '@anonymized_account To jest 3600 dla rodziny 2+1, ale zakładając składki odprowadzane, 1400 +153 rodzinne odpada, to bez względu na dochód masz 1530 zl',
  '- Nie mogę cały dzień chodzić w piżamie - pomyślałam, więc poszłam się położyć. #Lenistwo🙆',
  '@anonymized_account @anonymized_account Ofertę przedłużenis kontraktu ponoć dostał od Wisły, ale jej nie zaakceptował.',
  'RT @anonymized_account Tymczasem jak mi donoszą wiewiórki z Karpacza w Western City od wczoraj trwa gorączkowe poszukiwanie kamer i mikrofonów',
  '@anonymized_account @anonymized_account Kamilo jak patrzę na Ciebie to widzę obraz nędzy i rozpaczy',
  'Jest decyzja sądu ws. Stanisława Gawłowskiego. Polityk PO idzie do więzienia\\n@anonymized_account #wieszwiecej\\nhttps://t.co/evVvuT3qZO',
  '@anonymized_account @anonymized_account Piwiedz to Carrillo.Mitrović i Cywka to większe kozaki i przyszłość Wisły 😂',
  '@anonymized_account żebyście wy wytykali liczby wyjazdowe to śmiech na sali',
  '@anonymized_account @anonymized_account @anonymized_account @anonymized_account @anonymized_account A gdzie można zapoznać się z pana reportażem ?',
  '@anonymized_account @anonymized_account Pewnie jesteś jego agentem więc tym bardziej nie spodziewam się obiektywizmu',
  '@anonymized_account Wspaniale się udało. Dzięki, że to zorganizowałeś 🤗👏💪',
  '@anonymized_account A jeszcze chcą go na taczkach wywozić😁😁😀',
  'pies mi wpadł na pełnej kurwie do pokoju boże tak się przestraszyłam\\nmyślałam, że już po mnie przyszło fbi',
  '@anonymized_account Dziadek ubierz kapcie, siadaj w fotelu i skończ bredzić',
  'RT @anonymized_account Podobno ślina Krystyny Pawłowicz ma być przechowywana w Światowym Banku Nasion w Svalbard.\\nJak wzór genetyczny czysteg…',
  '@anonymized_account @anonymized_account @anonymized_account @anonymized_account Idź na typową projekcję z Ziemkiewiczem.',
  '@anonymized_account Jeżeli chcesz zobaczyć głupca to popatrz w lustro',
  '@anonymized_account Może są tam same schabowe?😂',
  '@anonymized_account jeśli nie podpisała stosownej umowy z zawodnikiem to piłkarz wybierze lepszą oferte',
  '@anonymized_account @anonymized_account Ile było wyjazdów na świt Wisły?  Bo chyba niewiele a na jednym byłem ale z tego co pamiętam to liga.',
  'Dziennikarka miażdży intelektualnie wysłannika @anonymized_account gdzie ja żyję',
  '@anonymized_account Rezerwowy bramkarz reprezentacji Kosowa :)',
  '@anonymized_account @anonymized_account Na chroma wystarczy wtyczke zainstalować. Pare sekund i gotowe :)',
  '@anonymized_account @anonymized_account Dlatego tam była sytuacja czarno-biała, a tu niekoniecznie 😜',
  '@anonymized_account Z drugiej strony przed zmianą przepisów był płacz, że jest karny + czerwona, karze się podwójnie i psuje to widowisko.',
  '@anonymized_account Takie było moje wrażenie, że sporo długich do rywala. Jakbyśmy zobaczyli skuteczność długich podań, to byśmy wiedzieli.',
  '@anonymized_account Hajto dostał na tacy zespół z ekstraklasy tylko za nazwisko i sobie nie poradził i nie dziwie się że nikt go już nie chce zatrudnić',
  '@anonymized_account beze mnie :( ja w robocie :( @anonymized_account',
  'Wiecie co? Jest mi ogromnie przykro i mam dosyć sama siebie',
  '@anonymized_account @anonymized_account @anonymized_account @anonymized_account @anonymized_account Co w tym takiego niesamowitego ?',
  '@anonymized_account @anonymized_account @anonymized_account @anonymized_account No to muszą ci nieźle płacić za wierszówki.',
  'Familiada:\\nStworzenia, które nie wydają żadnego odgłosu:\\n- Wąż \\n- Mucha\\n😂',
  '@anonymized_account @anonymized_account Haha od razu do reprezentacji 😂',
  'RT @anonymized_account Préstamo a un año con opción de compra para Ever Valencia y Cristian Echavarria al Wisla Cracovia de Polonia\\n@anonymized_account',
  '@anonymized_account @anonymized_account @anonymized_account Nie sędziował antyWisła Kraków tylko sędziował chujowo w obie strony.',
  '@anonymized_account @anonymized_account I po co te ubliżanie',
  '@anonymized_account @anonymized_account @anonymized_account Ty to robisz przede wszystkim, co widać po pierwszym tweecie.',
  '@anonymized_account @anonymized_account Macie prowokuj bo znowu będziesz płakał że ci prawdę powiem.',
  '@anonymized_account A muslalam ze tylko UKW ma jakieś problemy xd',
  'Nie ma w PiS wojowników? Tylko same cipy? No już patrzeć na to nie można#Kropka nad i MO',
  '@anonymized_account głowa do góry.Przegraliśmy bitwę ale nie wojnę :) Będzie dobrze :)',
  '@anonymized_account Zgodnie z zasadą, że co by nie zrobili to źle. Pojechał nie dobrze. Nie pojechał jeszcze gorzej.',
  '@anonymized_account To i Thiago trzeba powołać 🙃',
  '@anonymized_account Griezmann doprowadził swój zespół do MŚ, Hazard grał świetnie, ale o dobrych wynikach Belgii decydowały akcje innych zawodników.',
  '@anonymized_account jak można Góralskiego nazwać ofensywnym zawodnikiem ?',
  '@anonymized_account już mam folder na pulpicie przygotowany 😉',
  '@anonymized_account @anonymized_account Kaziu był wielkim zwolennikiem Vranjesa więc obstawiam Pogoń :)',
  '@anonymized_account @anonymized_account ale nawet jakby Niemcy wygrali to by to zmieniało tylko to że każdy remis by nam dawał awans a nie tylko 0:0 i1:1',
  '@anonymized_account Koniecznie! Zapraszamy na spacer z kawką 😃',
  'RT @anonymized_account „Ta aktorka ma 20 lat?!?! Jaka stara!!” \\n\\nChyba musimy się już do grobu pakować roczniku 98 😂👌🏻',
  'RT @anonymized_account Dzieci do szkoły odwiezione? \\nhttps://t.co/ByrZhHRwxe',
  '@anonymized_account Skoro o tym wiesz to chyba jednak nie potajemnie.',
  '@anonymized_account Teraz próbując znaleźć jakąś wzmiankę o zakazie czytam ze kibiców na meczu 4800.\\nFilipiak co? Zamknij ten burdel',
  '@anonymized_account Boję się Pana, skrajnie zidealizowany, teraz na bogs po mordzie się poobijać, limo pod oczami to chluba',
  '@anonymized_account Twoja stara, jest tak stara, że pamięta jak morze martwe było zaledwie chore',
  '@anonymized_account @anonymized_account @anonymized_account Można się wbić do Meghan i Harrego, trzeba tylko zaczekać aż wszyscy będą najebani',
  '@anonymized_account Biorąc pod uwagę występy Carlitosa przeciwko Jadze, będzie to strzał w bramkarza 😄',
  'RT @anonymized_account @anonymized_account Kłótnia z alter ego\\n\\"wypraszam sobie\\" ;)',
  '@anonymized_account przecież ten klub to AntyWisła więc czego Pan wymaga ?',
  'Głowacki ogląda zk przez pomyłkę, Przesmycki to przyznaje ale komisja kary nie cofa. Zmniejsza karę Gajosowi, po brutalnym wejściu w Kuna!!!',
  '@anonymized_account @anonymized_account @anonymized_account nie chodzi mi o dyktowane wpisy ale nie może Pan pisać niektórych rzeczy.Taka praca.',
  '@anonymized_account @anonymized_account A azbest stoi na szczycie ewolucji, debile',
  '@anonymized_account Wybacz Polsko,że ten hipokryta był u władzy.Zostaw nas w spokoju. 🇵🇱',
  '@anonymized_account @anonymized_account ale może czyta w internecie :-)',
  'Broniszewski szkoła Moskala.Gramy w \\"10\\" a on zmiany w 90 minucie robi...',
  '@anonymized_account Niezły zawodnik, ale w Legii by na niego nie spojrzeli.',
  '@anonymized_account P O L A N D !!',
  '@anonymized_account To nie ksiezyc, to cud! 🙈',
  '@anonymized_account @anonymized_account można też poprzestawiać pozycje zawodnikom, np Kiko przesunął Cywke na prawą obronę i dobrze na tym wyszedł.',
  '#Wypozyczeni Podbeskidzie - Garbarnia 0:0\\nPrzemysław Mystkowski grał 55 minut.',
  '@anonymized_account Na razie to w U-18 może grać czterech zawodników U-19. Na razie nie ma innej opcji, żeby to połączyć.',
  'Tata nie wiedział zd mam w czwartek urodziny thx m8',
  '@anonymized_account nie bede głaskał ale nie bede też do nazwy klubu dodawał \\"Cioty\\".Ale widocznie nie szanujesz klubu',
  '@anonymized_account @anonymized_account @anonymized_account Ani się nie obejrzysz jak ślad po was nie zostanie.',
  'RT @anonymized_account Jak się nazywa poseł, który bałamuci kobiety na miesiecznicach?\\nChwaliPięta.',
  '@anonymized_account @anonymized_account Dlatego to nie miało żadnego większego wpływu z żadnej ze stron.',
  '@anonymized_account A co na to bankster od frankowiczów @anonymized_account o wydatkach MON',
  '@anonymized_account Czyli tu nie ma co trenować, tu trzeba dzwonić ?',
  '@anonymized_account bardzo niedoceniany obrońca a umiejętności na czołówke ekstraklasy ma',
  '@anonymized_account @anonymized_account @anonymized_account oczywiście że to było słabe',
  '@anonymized_account i tak poznam tą tajemnice :) pewnie te zawodniczki ktore chcesz i w jakiej rundzie ? :)',
  '@anonymized_account @anonymized_account @anonymized_account Na temat tej panienki tak.',
  '@anonymized_account A widzieliście się wczesniej? 😂',
  '@anonymized_account @anonymized_account Zapewne ci, co grali przez większość rundy w CLJ i nie ponieśli ani jednej porażki.',
  '@anonymized_account Zaraz poszukam jabłecznika, może tez będzie 😂',
  '@anonymized_account Major Jach z PiSu też?',
  '@anonymized_account @anonymized_account @anonymized_account @anonymized_account Dajcie se po razie, bo wszyscy tu na to czekają 😂',
  '@anonymized_account @anonymized_account The best, czego tu nie rozumiecie',
  'Sieci, sieci, sieci komórkowe, media, media, media społecznościowe',
  '@anonymized_account nie lubisz tych dni kiedy trener na Ciebie nakrzyczy ?:D',
  '@anonymized_account Co ty człowieku pijesz z rana?',
  '@anonymized_account walka pies vs. kanapa z góry jest przegrana. Wszystkie to robią, tylko te lepiej wychowane kiedy właściciel nie widzi.',
  '@anonymized_account Bo pan Massimo jest znany z olewania niektórych rzeczy, na przykład murawy 😜',
  'Zapukał umówione 127 razy. Nikt nie otworzył. Wyszedł i spojrzał w okno. Tak, nie mylił się. Na parapecie stały 63 żelazka - znak wpadki.',
  '@anonymized_account @anonymized_account @anonymized_account Czapki z głów, zerwałeś się ze smyczy',
  '@anonymized_account #PiSkomuna - kurwa, zdzira!\\nChciwie w kieszeń Ci spozira\\nI wyciąga z niej dukaty. \\nChce tu Moskwę mieć. Na raty',
  '@anonymized_account To teraz pomyśl, jaki musiał być jego instat index do przerwy :D',
  '@anonymized_account @anonymized_account Pomagać można na inne sposoby.',
  'Co ty na zjebie bez godności @anonymized_account',
  '@anonymized_account @anonymized_account W razie czego dokopią się do tego Euro 2004 😁',
  '@anonymized_account Ja mam wrażenie ze kiko niema możliwości zmian bo Małecki ulubieniec kibiców ma większe poparcie niż kiko i zarząd',
  '@anonymized_account @anonymized_account @anonymized_account @anonymized_account ,publicznie się chwali że chodził do burdelu za swoje pieniądze. Kozak',
  '@anonymized_account To oglądaj Puchar Bałtyku :D Warto, choćby dla samego trofeum. Zerknij, jak ono wygląda :D',
  'JA JESTEM NORMALNY JA CHCE TYLKO ZAPOZOWAĆ Z ROWEREM PANI SYNA #topmodel',
  '@anonymized_account jak już coś to karny Kimmicha a nie wszystkie',
  '@anonymized_account @anonymized_account Jakiś konkret może? Jak Pan nie wie o czym mowa, to proszę nie zabierać głosu.',
  'RT @anonymized_account @anonymized_account Tomek ty i analizy? Ty i wnioski? Chłopie nie wiem co ty bierzesz ale zmnieksz dawkę o połowę...',
  '@anonymized_account Kto wie, czy w tym sezonie nie będzie jeszcze mniej.',
  '@anonymized_account Lub kibiców w Gliwicach 😜',
  '@anonymized_account na szczęście wy wychodziliście ze stadionu jak dostawaliście od Lecha, więc jesteście cali i zdrowi  @anonymized_account',
  '@anonymized_account @anonymized_account @anonymized_account uważaj stara ruro, bo Ci na żarcie w sejmie nie wystarczy.',
  '@anonymized_account Tak trzymać, merytorycznie i z chumorem',
  '@anonymized_account @anonymized_account To, że figurowal jako zawodnik Man City nie znaczy, że będzie potrafił grać.',
  '@anonymized_account W zasadzie co za różnica. Jeden wart drugiego😁😁',
  'RT @anonymized_account from: me\\nto: my tl\\n\\njedyne legendy to jonas brothers i hannah montana, miłego życia.',
  '@anonymized_account Zrezygnował? Wyjebali go wreszcie, tylko trzeba to było jakoś sprytnie zrobić, żeby nie było, że opozycja miała rację.',
  '@anonymized_account No tak właśnie mi się wydawało, ale widziałem tweeta, który sugerowałby co innego :)',
  '@anonymized_account @anonymized_account Jak Ty umiesz w światło!',
  '@anonymized_account I nie powiedziałem na zdrowie',
  '@anonymized_account Straszy redekcje karami gałgan jeden',
  'Serio ludzie już stoją pod biedronka po te maskotki XD',
  '@anonymized_account @anonymized_account Nikt jej nie potrafi powiedzieć, że dziennikarz to nie baba na rynku co handluje mięsem i drze ryja?',
  '@anonymized_account @anonymized_account gdyby Spartakus dzisiaj wygrał z KSZO to dalej byśmy nie byli pewni utrzymania.Na szczęście przegrali :)',
  '@anonymized_account myślałem że wszyscy kibice Realu kochają Ronaldo :) @anonymized_account',
  'Polaczenia wykonawcy Kombajn do zbierania kur po wioskach\\nhttps://t.co/Z1XVBeIzPo',
  '@anonymized_account Maczynski był tylko solidnym graczem w Wisle w tamtym sezonie a Wisla po 15 kolejkach w tamtym sezonie była faworytem do spadku.',
  'Pudło roku już znamy. Wczorajszy finał kobiet U-19, Hiszpania przegrywa 1:2 z Francją, doliczony czas i...\\nhttps://t.co/XLptHrcfUj',
  '@anonymized_account Dokładnie, ale remis dziś i zwycięstwo dwiema bramkami z Japonią na 100% daje awans (tak samo Kolumbia z Senegalem).',
  'RT @anonymized_account um jesli te plotki na temat finalu the originals to prawda to to bedzie kurwa najgorsze zakonczenie serialu w calym swiecie s…',
  '@anonymized_account @anonymized_account @anonymized_account Brawo grzechu za Twój powrót do żywych\\n W Rosji pokaż swoją moc',
  'Jak zdam prawko to będę błagać rodzine żeby mi się dołożyli do nissana k12 ten samochodzik jest taki mały i fajny xdq',
  '@anonymized_account skoro zarząd pozwala na takie cyrki to niestety potrwa to lata',
  '@anonymized_account @anonymized_account Jak.mam coś do kogoś to do tego kogoś mówię a nie w próżnię.',
  'Chyba trzeba to konto na @anonymized_account skasować, bo to się jeszcze czyimś spadkiem skończy 😳\\nhttps://t.co/8ZWu2gpd9m',
  '@anonymized_account @anonymized_account Widzisz jak na nas działa hawajska 😂 wspólny wróg jednoczy 💪',
  '@anonymized_account @anonymized_account Spadniemy !! Przecież nie ma Wolskiego !! Tak mówią dzieci na fb i tt a ja im wierze !:) 1 liga wita :)',
  '@anonymized_account Tego faceta nie ogarniam xd',
  '@anonymized_account @anonymized_account Ty pajacu, zmień sobie herb na pusty łeb.',
  '@anonymized_account @anonymized_account U mnie też i tego się boję.',
  'Mam straszną ochotę na sushi',
  '@anonymized_account J Szajben Wielgus była by na pewno lepszą',
  '@anonymized_account @anonymized_account Zdaję sobie tego sprawę ;)',
  '@anonymized_account @anonymized_account @anonymized_account @anonymized_account @anonymized_account @anonymized_account Niestety nie widziałem Cię na stadionie xD',
  'Beata #Mazurek w Sejmie na pytanie co myśli o pomyśle Kaczyńskiego o obniżkach wynagrodzeń: \\"Ja nic nie myślę\\". To słychać.',
  'O nIe ŚlUbU NiE bĘdZie zNoWu mAm oPrYsZcZkĘ',
  '@anonymized_account Filozofia miała być zmieniona i miało być więcej wychowanków a jak jest widzimy.',
  '@anonymized_account wiadomo czy Aga jutro zagra ? Bo wyglądało na skręcenie stawu skokowego :/',
  'Skurwysyny pisdzielskie  wasze słowo m-c: empatia',
  'jest moc jak kurwy zabiorą mi Unię Europejską ja zabiorę im żony i dzieci',
  '.@anonymized_account Dwukrotnie zamówili szkła o złej wadzie, raz uszkodzili przy montażu. Czekam miesiąc. Zero poczucia winy. Odradzam.👎😡',

In [8]:
class CustomTextClassificationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt",
        )

        return {
            "input_ids": encoding["input_ids"].flatten(),
            "attention_mask": encoding["attention_mask"].flatten(),
            "labels": torch.tensor(self.labels[idx], dtype=torch.long),
        }

In [9]:
# model_name = "distilbert-base-uncased"
model_name = "sdadas/polish-roberta-base-v2"
# model_name = "allegro/herbert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
# q_config = BitsAndBytesConfig(load_in_8bit=True)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, num_labels=2, device_map="auto",
    trust_remote_code=True, low_cpu_mem_usage=True,
    output_attentions=False, output_hidden_states=False,
    # quantization_config=q_config,
)
model.config.pad_token_id = tokenizer.pad_token_id

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/346 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: sdadas/polish-roberta-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [10]:
datasets = {
    "train": CustomTextClassificationDataset(texts=X_train, labels=y_train, tokenizer=tokenizer),
    "test": CustomTextClassificationDataset(texts=X_test, labels=y_test, tokenizer=tokenizer),
    "eval": CustomTextClassificationDataset(texts=X_eval, labels=y_eval, tokenizer=tokenizer)
}

In [11]:
# !inputs must be weighted as negative sentiment class (1) is undersampled

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)


class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")

        # weighted CE
        loss_fct = nn.CrossEntropyLoss(weight=weights_tensor)
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))

        return (loss, outputs) if return_outputs else loss


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {"accuracy": accuracy_score(labels, predictions)}


lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["query", "value"],
    lora_dropout=0.05,
    bias="none",
    task_type="SEQ_CLS",
)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)

print(model)

training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/Colab Notebooks/results",
    num_train_epochs=20,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    logging_dir="/content/drive/MyDrive/Colab Notebooks//logs",
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    learning_rate=2e-4,
    fp16=True,
)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=datasets["train"],
    eval_dataset=datasets["eval"],
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): RobertaForSequenceClassification(
      (roberta): RobertaModel(
        (embeddings): RobertaEmbeddings(
          (word_embeddings): Embedding(50001, 768, padding_idx=1)
          (token_type_embeddings): Embedding(1, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (position_embeddings): Embedding(514, 768, padding_idx=1)
        )
        (encoder): RobertaEncoder(
          (layer): ModuleList(
            (0-11): 12 x RobertaLayer(
              (attention): RobertaAttention(
                (self): RobertaSelfAttention(
                  (query): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): lora.Linear(
                    (base_layer): Linear(in_features=768, out_features=768, bias=True)
                    (lora_dropout): ModuleDict(
                      (default): Dropout(p=0.05, inplace=False)
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=768, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=768, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): RobertaSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): RobertaIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
                (intermediate_act_fn): GELUActivation()
              )
              (output): RobertaOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
      )
      (classifier): ModulesToSaveWrapper(
        (original_module): RobertaClassificationHead(
          (dense): Linear(in_features=768, out_features=768, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
          (out_proj): Linear(in_features=768, out_features=2, bias=True)
        )
        (modules_to_save): ModuleDict(
          (default): RobertaClassificationHead(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
            (out_proj): Linear(in_features=768, out_features=2, bias=True)
          )
        )
      )
    )
  )
)

In [12]:
trainer.train()

[transformers] `use_return_dict` is deprecated! Use `return_dict` instead!

TrainOutput(global_step=20080, training_loss=0.5105027255476141, metrics={'train_runtime': 1201.6058, 'train_samples_per_second': 133.688, 'train_steps_per_second': 66.844, 'total_flos': 2678089861201920.0, 'train_loss': 0.5105027255476141, 'epoch': 5.0})

In [13]:
eval_dataloader = DataLoader(datasets["test"], batch_size=8, shuffle=False, drop_last=False, num_workers=4)

all_predictions = []
all_labels = []

model.eval()
with torch.no_grad():
    for batch in eval_dataloader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        predictions = torch.argmax(outputs.logits, dim=-1)

        all_predictions.extend(predictions.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

accuracy = accuracy_score(all_labels, all_predictions)
print(f"Model Accuracy: {accuracy:.4f}")

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:424: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:432: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  self.check_worker_number_rationality()

Model Accuracy: 0.9234

In [14]:
with open("/content/drive/MyDrive/Colab Notebooks/hate_test_data.txt", "r", encoding="utf-8") as f:
    test_data = f.read().splitlines()

all_predictions = []

model.eval()
with torch.no_grad():
  for sentence in test_data:
      encoding = tokenizer(
          sentence,
          truncation=True,
          padding="max_length",
          max_length=128,
          return_tensors="pt",
      )

      input_ids = encoding["input_ids"].to(device)
      attention_mask = encoding["attention_mask"].to(device)

      outputs = model(input_ids=input_ids, attention_mask=attention_mask)
      predictions = torch.argmax(outputs.logits, dim=-1)

      all_predictions.extend(predictions.cpu().numpy())
print(all_predictions)

all_predictions = np.array(all_predictions, dtype=np.int32)

np.savetxt("/content/drive/MyDrive/Colab Notebooks/pred.csv", all_predictions, fmt='%d')

[np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(0)]

In [15]:
print(np.unique_counts(all_predictions))

UniqueCountsResult(values=array([0, 1], dtype=int32), counts=array([948,  52]))